
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-004
spec:
  selector:
    matchLabels:
      app: nginx-container-004
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-container-004
    spec:
      volumes:
        - name: nginx-volume-bind
          persistentVolumeClaim:
            claimName: nginx-volume-claim
        - name: foo
          configMap:
            name: game-demo
      containers:
      - name: nginx
        image: 288milan/jenkins-pipe-demo
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
          limits:
            memory: "250Mi"
        volumeMounts:
        #- name: nginx-volume-bind
        #  mountPath: /home
        - name: foo
          mountPath: "/home"
        env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
              optional: false # same as default; "mysecret" must exist
                            # and include a key named "username"
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
              optional: false 


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-004
  labels:
    app: nginx
spec:
  ports:
  - port: 8080
  selector:
    app: nginx-container-004
